eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
